#! /usr/bin/python3
from PySide2.QtWidgets import QApplication
#from PySide2.QtQuick import QQuickView
from PySide2.QtCore import QUrl
from PySide2.QtGui import QIcon
from PySide2.QtQml import QQmlApplicationEngine

import sys
sys.path.append('/usr/share/lliurex-cdlocker/')

import LliurexCDLocker


if __name__=="__main__":

	app = QApplication()
	engine = QQmlApplicationEngine()
	context=engine.rootContext()
	bridge=LliurexCDLocker.Bridge(sys.argv[1])
	context.setContextProperty("con", bridge)

	url = QUrl("/usr/share/lliurex-cdlocker/rsrc/llxCDLocker.qml")

	engine.load(url)
	if not engine.rootObjects():
		sys.exit(-1)

	app.setWindowIcon(QIcon("/usr/share/icons/hicolor/scalable/apps/lliurex-cdlocker.svg"));
	engine.quit.connect(app.quit)
	sys.exit(app.exec_())
	
